export const AGREGAR_PERSONAJE = "AGREGAR_PERSONAJE";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const GET_CHARACTER_DETAIL = "GET_CHARACTER_DETAIL";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const FILTER = "FILTER";
export const ORDER = "ORDER";
export const GET_FAVORITES = "GET_FAVORITES";
